name: Continous Deployment
on:
  push:
    branches: [develop]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: Install Dependencies
        run: npm install
        working-directory: backend
      - name: Build
        run: npm run-script build
        working-directory: backend
      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: backend/dist
  dockerize:
    needs: build
    env:
      FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      DISCORD_CLIENT_TOKEN: ${{ secrets.DISCORD_CLIENT_TOKEN }}
      TEST_GUILD_ID: ${{ secrets.TEST_GUILD_ID }}
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Download build as artifact
        uses: actions/download-artifact@v1
        with:
          name: dist
          path: backend/dist
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Realdegrees Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.realdegrees.dev
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: backend
          file: docker/Dockerfile
          push: true
          tags: docker.realdegress.dev/cu-bot:latest
